### ISSUE TITLE
Support for React.forwardRef

### ISSUE THREAD

**Issue by matthewchigira** [UXPin/uxpin-merge-tools#205]
One of our customers has a DS that is relying on the use of [React's Forwarding Refs](https://reactjs.org/docs/forwarding-refs.html)

There are two ways of declaring forwards refs that they are using:
`React.forwardRef`
`React.FC<Props>`

**Comment by naohiro-t** [comment]
I just came across with this when I tried to use merge with [a component from Storybook design system](https://github.com/storybookjs/design-system/blob/5c5387b82a3a48ad74d0805c315e73a6ffc93c2b/src/components/tag/TagList.tsx#L35)
Looks like there are 2 things we need to handle at least 

1. To be able to detect component declaration from

https://github.com/UXPin/uxpin-merge-tools/blob/8b8843405d294b8efb24fb7611e9b5bc370a3c51/packages/uxpin-merge-cli/src/steps/serialization/component/implementation/typescript/component/getComponentDeclaration.ts#L19-L24

Because it is not function nor class declaration, we can't detect component declaration. `const Component = forwardRef..` is categorized as `CallExpression` in typescript.

2. Serialize props also won't work with current implementation. (Didn't look into too deep for this, but it at least didn't work even if we can find the component declaration)
